### ISSUE TITLE
Fix context when updating / cascade-saving objects

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6736]
### Issue Description

The introduction of making the trigger context accessible when saving an object (https://github.com/parse-community/parse-server/issues/6459) did not account for 2 use cases:

1. No `context` is set when saving an existing object as discovered by @marcinjakubowski https://github.com/parse-community/parse-server/issues/6459#issuecomment-642933120:
```
const obj = new Parse.Object("TestObject");
await obj.save(null);
await obj.save(null, { context: { a: 'a' } });
```

2. The `context` is not set when cascade-saving objects so that `context` is inherited by child objects (`obj2` in this example) as discovered by @davbeck https://github.com/parse-community/parse-server/issues/6459#issuecomment-644429993:
```
const obj = new Parse.Object("TestObject");
const obj2 = new Parse.Object("TestObject2");
obj.set("obj2", obj2);
await obj.save(null, { context: { a: 'a' } });
```

**TODOs:**
- [x] Changes in Parse JS SDK https://github.com/parse-community/Parse-SDK-JS/pull/1186
- [ ] Changes in Parse Server https://github.com/parse-community/parse-server/pull/6735
- [x] _no doc changes necessary_

**Comment by mtrezza** [comment]
@dplewis When can we merge these PRs? I feel the more time passes, the harder it gets to track and eventually merge all these changes. Especially since we are already getting PRs (https://github.com/parse-community/parse-server/pull/6764) that run in parallel to the PRs here.
