### ISSUE TITLE
Improve contribution guide

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7100]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The Contribution Guide could benefit from an overhaul to:
- be more accessible for new developers by reducing required pre-existing knowledge
- mitigate bug risks by documenting processes for common changes
- facilitate code quality by adding code style guidelines

The contribution guide currently only contains descriptions of the technical set-up required to make changes to Parse Server, described in way that assumes a level of pre-existing knowledge about tools and processes that has shown in some cases to discourage new developers from creating PRs. Parse is not just an entry point for new developers for its use as a backend but also when it comes to its development and making first steps into open-source contribution. A more accessible guide benefits both developers and further development of Parse.

### Suggested changes

- [ ] Add process: Add new Parse Error -> #7075
- [ ] Add process: Add new Parse Server configuration parameter -> #7075
- [ ] Add: Code style guide
- [ ] Add: PR guide (GitHub guide is too verbose and not suitable as a reference for new developers)
- [ ] Reformat document to increase readability
- [ ] Rewrite guides into step-by-step instructions to help new developers

**Comment by Moumouls** [comment]
@julianvogels could help us to improve this one 🙂 (ref: https://community.parseplatform.org/t/what-you-love-about-parse-and-also-of-the-difficulties-you-have-encountered/1140/5 )

**Comment by Moumouls** [comment]
@mtrezza on my first contribution, I remember that running `npm run watch` and that playing with `npm test` was straight forward.

Today, systems like `Jest` can onboard the compilation to only need `npm test` and get rid off the `npm run watch`.

I know https://www.npmjs.com/package/concurrently that allow to execute 2 commands at the same time.

I found that Jasmine do not have watch mode: https://github.com/jasmine/jasmine-npm/issues/5

So by adding `nodemon` + `concurrently` + `npm test` + `npm run watch` could do the trick.

i also found that we can add the babel compiler to our jasmine.json: https://github.com/piecioshka/test-jasmine-babel/blob/master/test/jasmine.json

**Comment by mtrezza** [comment]
I stumbled upon an open source, multi-lingual, multi-environment guide for first contributors that we could link to in our contribution guide: https://github.com/firstcontributions/first-contributions



@TomWFox what's your opinion as chief docs officer?

**Comment by TomWFox** [comment]
Looks neat, there are some parts which wouldn't apply for our projects (e.g. [make changes](https://github.com/firstcontributions/first-contributions#make-necessary-changes-and-commit-those-changes) - could cause a bit of confusion but perhaps easily outweighed by the benefit of the resource.

**Comment by mtrezza** [comment]
@dblythy Would you want to make a PR to add your [blog post](https://blog.parseplatform.org/learn/tutorial/community/nodejs/2021/02/14/How-to-start-contributing-to-Parse-Server.html) to the contribution guide, for the reasons outlined in the [comment](https://community.parseplatform.org/t/what-you-love-about-parse-and-also-of-the-difficulties-you-have-encountered/1140/11)?

**Comment by dblythy** [comment]
I would be happy to work on it!

**Comment by mtrezza** [comment]
Great! In terms of modification, it should transition from its current form of anecdotal account to a guide:
- more compact instead of verbose prose format (use lists, 1-2-3 step-by-step)
- imperative form instead of 1st person reference (e.g. "Do this and that" instead of "I did this and that")
- shape it into community editable form, expecting that others will amend and refine it in the future
