### ISSUE TITLE
OAuth test fails due to Twitter API issue

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7470]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Currently, the OAuth test fails due to an issue with the Twitter API endpoint that is used for testing a failed OAuth response.
The response is an incorrectly formatted JSON string, so parsing fails.

This happened at least once some time ago, so the endpoint to test against has been changed. If this keeps happening with the Twitter API, we may change to an OAuth API endpoint of another provider for testing.

### Steps to reproduce
Run test
```
GET https://api.twitter.com/1.1/account/settings.json
```

### Actual Outcome
```
{"errors":"{\"message\":\"Could not authenticate you\",\"code\":32}"}
```

### Expected Outcome
```
{
    "errors": [
        {
            "code": 32,
            "message": "Could not authenticate you."
        }
    ]
}
```

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `master` https://github.com/parse-community/parse-server/commit/1594afec6421bea31e732dff9b21eb099898bc3a
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `n/a`
- SDK version: `n/a`

### Logs

(none)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
