### ISSUE TITLE
Security review of 3rd party services

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7956]
We are doing our annual security review of 3rd party services. The goal is to remove permissions of services that are no longer used in this repository's CI workflow.

Services that need to be reviewed:

- [x] Travis CI for Open Source -> not used
- [x] Coveralls -> not used
- [x] StyleCI -> not used
- [x] Travis CI -> not used
- [x] AppVeyor -> not used
- [x] AppVeyor CI -> not used
- [x] CircleCI -> not used
- [x] Code Climate -> not used
- [x] Packagist -> not used
