### ISSUE TITLE
Parse Server 6 release

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8225]
# Parse Server 6

This is to prepare for Parse Server 6 release in Jan 2023.

## Schedule

- Nov 2022: Merge breaking changes into `alpha` to create `6.0.0-alpha` releases
- Dec 2022:
  1. Feature freeze for `alpha` branch until Parse Server 6.0 release
  2. Merge `beta` into `release` to release last Parse Server 5 stable version before LTS
  3. Merge `alpha` into `beta` to release `6.0.0-beta`
- Jan 2023: Merge `beta` into `release` to release `6.0.0`

## Issues / PRs to merge in Nov 2022

The following items are required or reasonable to do before a major release, since they involve breaking changes or relate to obsolete features that should be dropped. The list does not consider features or bugs that are unrelated to the aforementioned aspects and can therefore be merged at any time, unrelated to a major release.

### Required

- [x] Remove deprecations
  - [x] https://github.com/parse-community/parse-server/issues/8268
  - [x] https://github.com/parse-community/parse-server/issues/8269
  - [x] https://github.com/parse-community/parse-server/issues/8270
  - [x] https://github.com/parse-community/parse-server/issues/8271
- [x] https://github.com/parse-community/parse-server/issues/8081
- [x] parse-community/parse-server#8272
- [x] parse-community/parse-server#8273
- [x] parse-community/parse-server#8275
- [x] https://github.com/parse-community/parse-server/issues/8255
- [x] https://github.com/parse-community/parse-server/issues/8276
- [x] https://github.com/parse-community/parse-server/issues/7527
- [x] https://github.com/parse-community/parse-server/issues/8218
- [x] https://github.com/parse-community/parse-server/issues/8380
- [x] https://github.com/parse-community/parse-server/issues/8360
- [x] https://github.com/parse-community/parse-server/issues/8330
- [x] https://github.com/parse-community/parse-server/pull/8408
- [x] https://github.com/parse-community/parse-server/issues/8412

### Optional (planned)

- [x] https://github.com/parse-community/parse-server/issues/7575
- [x] https://github.com/parse-community/parse-server/issues/8245
- [ ] ~~https://github.com/parse-community/parse-server/issues/7434~~ (not a braking change)
- [ ] ~~https://github.com/parse-community/parse-server/pull/8153~~ (not a braking change)
- [ ] ~~https://github.com/parse-community/parse-server/issues/8027~~ (not a breaking change)
- [ ] https://github.com/parse-community/parse-server/pull/7446
- [x] https://github.com/parse-community/docs/issues/943

### Optional (to be discussed)
- [x] parse-community/parse-server#8274
- [x] https://github.com/parse-community/parse-server/issues/7042
- [ ] ~~Remove Node 14 support (EOL will be in Apr 2023)~~ (we'll keep Node 14 until Parse Server 7 (2024))
- [ ] https://github.com/parse-community/parse-server/issues/7979 (likely a huge effort and a major change that should go though alpha / beta testing first)
- [ ] https://github.com/parse-community/parse-server/pull/7440 (major change affecting also Parse client SDKs?)
- [ ] https://github.com/parse-community/parse-server/issues/8017 (just a nice-to-have for the new major release)

**Comment by dblythy** [comment]
**Some suggestions for breaking changes (alongside the current deprecations, https://github.com/parse-community/parse-server/blob/alpha/DEPRECATIONS.md):**

- Nested objects encoding change: https://github.com/parse-community/parse-server/pull/8209
- Disable auth adapters by default: https://github.com/parse-community/parse-server/issues/7952#issuecomment-1110495409
- Remove httpRequest entirely: https://github.com/parse-community/parse-server/issues/7589
- Change sessionToken to JWT (needs SDK support): https://github.com/parse-community/parse-server/issues/6390
- Remove GraphQL from codebase: https://github.com/parse-community/parse-server/issues/7979
- Modernize codebase, increase lint rules: https://github.com/parse-community/parse-server/issues/7563

**Some suggestions for some nice-to-have features:**

- New auth adapters + MFA: https://github.com/parse-community/parse-server/pull/8156
- expose config: https://github.com/parse-community/parse-server/issues/7869
- Global rate limiter: https://github.com/parse-community/parse-server/pull/8174
- Add dot notation by default to cloud code: https://github.com/parse-community/Parse-SDK-JS/pull/1484
- Modernize API template: https://github.com/parse-community/parse-server/issues/8017
- Parallel include: https://github.com/parse-community/parse-server/issues/7981

**Comment by mtrezza** [comment]
I've added your suggestions to the list above, except:
- https://github.com/parse-community/parse-server/issues/6390 --> could that be done without being a breaking change? if this is a more complex issue and we wouldn't want to rush this
- https://github.com/parse-community/parse-server/issues/7869 --> is this a breaking change? if not we can merge this anytime unrelated to the 6 release
- https://github.com/parse-community/parse-server/issues/7563 --> this is an internal change I assume? so maybe not breaking
- https://github.com/parse-community/parse-server/pull/8174 --> seems like a feature we can merge at anytime; from the discussion there I'm not sure we can turn this on by default, so maybe this will stay an optional feature anyway
- https://github.com/parse-community/Parse-SDK-JS/pull/1484 --> is this breaking?
- https://github.com/parse-community/parse-server/issues/8017 --> purely cosmetic, but certainly nice-to-have with a new release

**Comment by dblythy** [comment]
The feature section are just some suggestions for features we can aim to ship by Parse Server 6, not necessarily breaking.

The problem with parse-community/parse-server#7563 is that it will result in a lot of open PRs having huge merge conflicts, so internally breaking in a way. Maybe we can aim to close all PRs as complete or stale by V6, and do the overhaul of modernizing the codebase in V6.0.1, and then normal PRs can continue.

**Comment by mtrezza** [comment]
Yes, parse-community/parse-server#7563 is somewhat complex; we'd want to a void 1 huge PR so we'd try to section the code base and modernize section by section. This way we would also require only selected PRs to be merged.

**Comment by mtrezza** [comment]
I haven't looked into parse-community/parse-server#7979, it seems like a large effort. Given the other (required and planned) tasks we already have, it seems a bit much? I estimate that alone to take ~2-3 months getting done on the side.

**Comment by dblythy** [comment]
parse-community/parse-server#7981, parse-community/parse-server#8202 would be nice too.

Perhaps we can continue the discussion after V6 around parse-community/parse-server#7563.

Yes, perhaps parse-community/parse-server#7979 is a bit too ambitious to be released for V6.

**Comment by dblythy** [comment]
I guess the features are probably lower priority as they can always be shipped in Parse Server 6.0.1

**Comment by mtrezza** [comment]
Agree. What about https://github.com/parse-community/parse-server/issues/7527, could that be breaking / easier to implement as breaking?

**Comment by dblythy** [comment]
Yes, I think that is a good one. We can support it as a non-breaking change, but it's not really ideal to have 2 different startup methods, one that exposes routes before they are ready

**Comment by mtrezza** [comment]
Added to "planned".

**Comment by cbaker6** [comment]
parse-community/parse-server#7440 should be considered IMO. I don’t see any PR’s open for any of the alternatives others discussed in the linked thread

**Comment by mtrezza** [comment]
Added to "tbd". Seems to require further discussion and may affect Parse client SDKs? So maybe something we should take our time with and tackle in 2023, but that's definitely an important fix and improvement.

**Comment by cbaker6** [comment]
I believe the update for redis should be considered parse-community/parse-server#7987. It will be a breaking change (see [migration guide](https://github.com/redis/node-redis/blob/redis%404.0.0/docs/v3-to-v4.md), particularly the [client configuration guide](https://github.com/redis/node-redis/blob/redis%404.0.0/docs/client-configuration.md)) unless someone provides a converter from the old-style config options to the new redis options. The version of redis the server supports was released 4/21 which is pretty old.

**Comment by mtrezza** [comment]
Good one, added to "planned".

**Comment by mtrezza** [comment]
Removed https://github.com/parse-community/parse-server/issues/7589 from "Optional (planned)", since it's [unrelated](https://github.com/parse-community/parse-server/issues/7589#issuecomment-1300427118) to Parse Server 6 release.

**Comment by mtrezza** [comment]
@parse-community/server 

All required PRs (and a few of the optional PRs) for Parse Server 6 have been merged. Thanks everyone for their work.

If there is no additional suggestion, we'll release Parse Server 6 with the commits on the alpha branch.

**Comment by dblythy** [comment]
Yep, I think we're ready to go!

**Comment by mtrezza** [comment]
Presumed release date is Jan 30 or 31, since we're also consolidating the legal notes and that takes some time. At least we'll still be in Jan, so apart from skipping the beta phase we're on schedule. Nice!

**Comment by mtrezza** [comment]
Closing, release published
